Add end2end part to make it accessible to more users
nf-core/tfactivity pull request #18
Opened 2024-09-02 20:14 UTC by LeonHafner

I left the file paths in, so you can use the same files on the server @nictru.
We have to discuss somethings in our next meeting (e.g. no apptainer for chipseq, good testing data, non default parameters).

2024-09-05 09:10 UTC, nictru commented
LGTM so far

2024-11-28 10:05 UTC, nictru requested changes
Please add shebang and pipeline versions, so that external pipeline updates can't break our stuff

2024-11-28 10:05 UTC, nictru commented on assets/end_to_end.py
> +    /nfs/home/students/l.hafner/inspect/tfactivity/dev/main.nf \
Not great

2025-01-04 19:28 UTC, LeonHafner commented
https://github.com/nf-core/tfactivity/pull/24 should be merged first.

2025-03-06 14:53 UTC, LeonHafner commented on assets/end_to_end.py
> +    -r 45ba08d995 \
Probably we can use `-latest` here or don't use a revision at all?

2025-03-06 15:14 UTC, LeonHafner commented on assets/end_to_end.py
> +    -r 73a5304872 \
This is currently hardcoded to the latest commit in this PR: https://github.com/nf-core/chipseq/pull/438
See here for the commit: https://github.com/nf-core/chipseq/commit/73a5304872a3abfc2c173d250426d48e62b6a645

These changes are necessary for our end2end pipeline (as long as we don't get rid of the `skip_multiqc` flag) and are currently only in the `dev` branch of the `nf-core/chipseq` pipeline. Once a new release of `nf-core/chipseq` is available, we can update this and use the stable version as the revision.

2025-03-07 09:45 UTC, LeonHafner commented on assets/end_to_end.py
> +    -r 45ba08d995 \
Since we are still "stuck on dev" it will produce an error when running without specifying an explicit revision.

2025-03-07 09:46 UTC, LeonHafner commented on assets/end_to_end.py
> +    -r 73a5304872 \
Changed it to the most recent commit hash in the `dev` branch on `nf-core/chipseq`.

2025-03-13 09:03 UTC, nictru approved these changes

2025-03-13 09:03 UTC, merged